### ISSUE TITLE
Postfix example

### ISSUE THREAD

**Issue by setiseta** [n3wtype/mailman3-docker#1]
Hello,

can you please provide a example how to integrate those docker containers with postfix?
would be nice.

Kind Regards,
Sebastian

**Comment by n3wtype** [comment]
Hello,

sure I will add some info into README.md. Unfortunately it's manual process as mailman doesn't support api call to get (reported issue under https://gitlab.com/mailman/mailman/issues/305).

Just to get it started, you need to create following transport-map for your postfix configuration. <list> should be substituted with your mailing list name and x.x.x.x with your docker public IP address. Hope it's helpful.

<list>@sitel.net.pl               lmtp:[x.x.x.x]:8024
<list>-bounces@sitel.net.pl       lmtp:[x.x.x.x]:8024
<list>-confirm@sitel.net.pl       lmtp:[x.x.x.x]:8024
<list>-join@sitel.net.pl          lmtp:[x.x.x.x]:8024
<list>-leave@sitel.net.pl         lmtp:[x.x.x.x]:8024
<list>-owner@sitel.net.pl         lmtp:[x.x.x.x]:8024
<list>-request@sitel.net.pl       lmtp:[x.x.x.x]:8024
<list>-subscribe@sitel.net.pl     lmtp:[x.x.x.x]:8024
<list>-unsubscribe@sitel.net.pl   lmtp:[x.x.x.x]:8024

**Comment by n3wtype** [comment]
Hello,

sure I will add some info into README.md. Unfortunately it's manual process as mailman doesn't support api call to get transport-map (reported issue under https://gitlab.com/mailman/mailman/issues/305).

Just to get it started, you need to create following transport-map for your postfix configuration for each of your list. LIST should be substituted with your mailing list name, DOMAIN with domain name and x.x.x.x with your docker public IP address. Hope it would be helpful.

LIST@DOMAIN lmtp:[x.x.x.x]:8024
LIST-bounces@DOMAIN lmtp:[x.x.x.x]:8024
LIST-confirm@DOMAIN lmtp:[x.x.x.x]:8024
LIST-join@DOMAIN lmtp:[x.x.x.x]:8024
LIST-leave@DOMAIN lmtp:[x.x.x.x]:8024
LIST-owner@DOMAIN lmtp:[x.x.x.x]:8024
LIST-request@DOMAIN lmtp:[x.x.x.x]:8024
LIST-subscribe@DOMAIN lmtp:[x.x.x.x]:8024
LIST-unsubscribe@DOMAIN lmtp:[x.x.x.x]:8024
